"""Public API for the opt-in LegalMCQ three-role workflow."""

from .adapter import BenchmarkRecordAdapter, LeakGuard, request_only
from .agent import (
    EvidenceProvider,
    LegalMCQAgent,
    LegalMCQPolicy,
    PROMPT_VERSION,
    SolverTimeoutCircuitBreaker,
)
from .clients import (
    LegalModelClientError,
    LegalRoleClients,
    build_openai_role_clients,
    resolve_role_configs,
)
from .decision import DecisionValidation, DecisionValidator
from .evidence import (
    LegalEvidenceAdapterError,
    OathAuditedEvidenceProvider,
    adapt_audited_evidence,
)
from .evaluation import (
    LegalMCQEvaluationRecord,
    evaluate_case,
    summarize_records,
)
from .models import (
    AnswerStatus,
    Citation,
    ClaimAssessment,
    CONTROLLER_PROTOCOL_VERSION,
    CONTROLLER_PROTOCOL_V2_VERSION,
    ControllerPlan,
    EvaluationCase,
    EvaluationOracle,
    LegalAgentError,
    LegalAgentErrorCode,
    LegalAnswer,
    LegalEvidence,
    LegalIssue,
    LegalMCQRunResult,
    LegalOption,
    LegalQuestionRequest,
    OptionAssessment,
    ParsedLegalQuestion,
    QuestionType,
    SOLVER_PROTOCOL_VERSION,
    SOLVER_PROTOCOL_V2_VERSION,
    VERIFIER_PROTOCOL_VERSION,
    SolveMode,
    SolverDecision,
    VerificationResult,
)
from .parser import format_question, parse_question_text, parse_request
from .skills import LegalSkillRegistry, SkillDescriptor

__all__ = [
    "AnswerStatus",
    "BenchmarkRecordAdapter",
    "Citation",
    "ClaimAssessment",
    "CONTROLLER_PROTOCOL_VERSION",
    "CONTROLLER_PROTOCOL_V2_VERSION",
    "ControllerPlan",
    "DecisionValidation",
    "DecisionValidator",
    "EvaluationCase",
    "EvaluationOracle",
    "EvidenceProvider",
    "LegalAgentError",
    "LegalAgentErrorCode",
    "LegalAnswer",
    "LegalEvidence",
    "LegalIssue",
    "LegalModelClientError",
    "LegalMCQAgent",
    "LegalMCQEvaluationRecord",
    "LegalMCQPolicy",
    "LegalMCQRunResult",
    "LegalOption",
    "LegalQuestionRequest",
    "LegalRoleClients",
    "LegalSkillRegistry",
    "LegalEvidenceAdapterError",
    "LeakGuard",
    "OptionAssessment",
    "OathAuditedEvidenceProvider",
    "PROMPT_VERSION",
    "ParsedLegalQuestion",
    "QuestionType",
    "SOLVER_PROTOCOL_VERSION",
    "SOLVER_PROTOCOL_V2_VERSION",
    "VERIFIER_PROTOCOL_VERSION",
    "SolveMode",
    "SolverTimeoutCircuitBreaker",
    "SolverDecision",
    "SkillDescriptor",
    "VerificationResult",
    "adapt_audited_evidence",
    "build_openai_role_clients",
    "evaluate_case",
    "format_question",
    "parse_question_text",
    "parse_request",
    "request_only",
    "resolve_role_configs",
    "summarize_records",
]
